apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cz3n9kc8e-java-springboot 
  janus-idp.io/tekton: cz3n9kc8e-java-springboot
  backstage.io/kubernetes-id: cz3n9kc8e-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cz3n9kc8e-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml