apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cz3n9kc8e-java-springboot
  janus-idp.io/tekton: cz3n9kc8e-java-springboot
  backstage.io/kubernetes-id: cz3n9kc8e-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cz3n9kc8e-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
